from __future__ import annotations

from pathlib import Path

import pytest

from backend.meshing.configuration import (
    MeshingConfiguration,
    build_block_mesh_dict,
    build_snappy_hex_mesh_dict,
    list_meshing_surfaces,
    suggest_meshing_configuration,
    validate_meshing_configuration,
    write_meshing_dictionaries,
)


def write_tetrahedron(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """solid tetrahedron
facet normal 0 0 -1
 outer loop
  vertex 0 0 0
  vertex 0 1 0
  vertex 1 0 0
 endloop
endfacet
facet normal 0 -1 0
 outer loop
  vertex 0 0 0
  vertex 1 0 0
  vertex 0 0 1
 endloop
endfacet
facet normal -1 0 0
 outer loop
  vertex 0 0 0
  vertex 0 0 1
  vertex 0 1 0
 endloop
endfacet
facet normal 1 1 1
 outer loop
  vertex 1 0 0
  vertex 0 1 0
  vertex 0 0 1
 endloop
endfacet
endsolid tetrahedron
""",
        encoding="utf-8",
    )


def build_case(tmp_path: Path) -> Path:
    case = tmp_path / "case"
    (case / "system").mkdir(parents=True)
    write_tetrahedron(case / "constant" / "triSurface" / "part.stl")
    return case


def test_surface_discovery_and_automatic_domain_sizing(tmp_path):
    case = build_case(tmp_path)

    assert list_meshing_surfaces(case) == [
        {"text": "constant/triSurface/part.stl", "value": "triSurface/part.stl"}
    ]
    config = suggest_meshing_configuration(case, "triSurface/part.stl", fineness=5)

    assert config.bounds == pytest.approx((-0.2, 1.2, -0.2, 1.2, -0.2, 1.2))
    assert config.base_cells == (52, 52, 52)
    assert config.refinement_min == 2
    assert config.refinement_max == 3
    assert config.surface_layers == 3


def test_generated_dictionaries_contain_reviewed_controls(tmp_path):
    case = build_case(tmp_path)
    config = suggest_meshing_configuration(case, "triSurface/part.stl", fineness=3)

    block_dict = build_block_mesh_dict(config)
    snappy_dict = build_snappy_hex_mesh_dict(config)

    assert "hex (0 1 2 3 4 5 6 7) (36 36 36)" in block_dict
    assert 'file "part.stl";' in snappy_dict
    assert "level (2 3);" in snappy_dict
    assert '"part.*"' in snappy_dict
    assert "nSurfaceLayers 3;" in snappy_dict
    assert "caseDicts/mesh/generation/meshQualityDict.cfg" in snappy_dict
    assert "insidePoint         (" in snappy_dict


@pytest.mark.parametrize(
    "version,keyword,absent",
    [
        ("12", "insidePoint", "locationInMesh"),
        ("13", "insidePoint", "locationInMesh"),
        ("v2312", "locationInMesh", "insidePoint"),
        ("v2412", "locationInMesh", "insidePoint"),
        ("2412", "locationInMesh", "insidePoint"),
    ],
)
def test_region_point_matches_configured_openfoam_family(
    tmp_path, version, keyword, absent
):
    case = build_case(tmp_path)
    config = suggest_meshing_configuration(
        case, "triSurface/part.stl", openfoam_version=version
    )
    assert validate_meshing_configuration(config).openfoam_version == version
    preview = build_snappy_hex_mesh_dict(config)
    assert f"{keyword:<19} (" in preview
    assert absent not in preview
    write_meshing_dictionaries(case, config)
    assert (case / "system" / "snappyHexMeshDict").read_text(
        encoding="utf-8"
    ) == preview


def test_dictionary_writes_are_atomic_and_preserve_backups(tmp_path):
    case = build_case(tmp_path)
    old_block = case / "system" / "blockMeshDict"
    old_block.write_text("original\n", encoding="utf-8")
    config = suggest_meshing_configuration(case, "triSurface/part.stl")

    result = write_meshing_dictionaries(case, config)

    assert {path.name for path in result.paths} == {
        "blockMeshDict",
        "snappyHexMeshDict",
    }
    assert result.backup_directory is not None
    assert (result.backup_directory / "blockMeshDict").read_text(
        encoding="utf-8"
    ) == "original\n"
    assert "Generated by FOAMTrame" in old_block.read_text(encoding="utf-8")
    assert result.staged_surface == case / "constant" / "geometry" / "part.stl"
    assert (
        result.staged_surface.read_bytes()
        == (case / "constant" / "triSurface" / "part.stl").read_bytes()
    )
    assert not list((case / "system").glob("*.tmp"))


def test_native_case_geometry_is_used_without_a_copy(tmp_path):
    case = build_case(tmp_path)
    native = case / "constant" / "geometry" / "native.stl"
    write_tetrahedron(native)
    options = list_meshing_surfaces(case)
    assert options[0] == {
        "text": "constant/geometry/native.stl",
        "value": "geometry/native.stl",
    }

    config = suggest_meshing_configuration(case, "geometry/native.stl")
    result = write_meshing_dictionaries(case, config)

    assert result.staged_surface is None
    assert 'file "native.stl";' in (case / "system" / "snappyHexMeshDict").read_text(
        encoding="utf-8"
    )


def test_imported_surface_does_not_replace_existing_native_geometry(tmp_path):
    case = build_case(tmp_path)
    native = case / "constant" / "geometry" / "part.stl"
    write_tetrahedron(native)
    config = suggest_meshing_configuration(case, "triSurface/part.stl")

    with pytest.raises(ValueError, match="already exists"):
        write_meshing_dictionaries(case, config)

    assert not (case / "system" / "blockMeshDict").exists()


@pytest.mark.parametrize(
    "configuration, message",
    [
        (
            MeshingConfiguration(
                "triSurface/part.stl", (0, 0, 0, 1, 0, 1), (10, 10, 10), 2, 3, 3
            ),
            "minimum",
        ),
        (
            MeshingConfiguration(
                "triSurface/part.stl", (0, 1, 0, 1, 0, 1), (0, 10, 10), 2, 3, 3
            ),
            "cell counts",
        ),
        (
            MeshingConfiguration(
                "triSurface/part.stl", (0, 1, 0, 1, 0, 1), (10, 10, 10), 4, 3, 3
            ),
            "refinement",
        ),
        (
            MeshingConfiguration(
                "../part.stl", (0, 1, 0, 1, 0, 1), (10, 10, 10), 2, 3, 3
            ),
            "surface",
        ),
    ],
)
def test_invalid_meshing_configuration_is_rejected(configuration, message):
    with pytest.raises(ValueError, match=message):
        validate_meshing_configuration(configuration)
